spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plai_dev
    username: plai_dev_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: plaiAssociation@gmail.com
    password: Plai1234.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true